version: '3'
services: 
    web:
        build: ./.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        links: 
            - api
    api:
        build: ./src/api/.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports: 
            - 6001:6001
            - 6002:6002
    func:
        build: ./src/func/.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"