version: '3'
services: 
    web:
        build: ./.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        links: 
            - api
        ports:
            - 5000:5000
            - 5001:5001
    api:
        build: ./src/api/.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports: 
            - 6001:6001
            - 6002:6002
        links:
            - func
            - azurite
            - cosmos
    func:
        build: ./src/func/.devcontainer
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - 7071:7071
        links:
            - azurite
            - cosmos
    azurite:
        image: "mcr.microsoft.com/azure-storage/azurite"
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
    cosmos:
        image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
        ports:
            - "8081:8081"
            - "10251:10251"
            - "10252:10252" 
            - "10253:10253"
            - "10254:10254"